[package]
name                   = "identus-wasm-did"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish.workspace      = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
identus-did.workspace  = true
wasm-bindgen.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true

[lints]
workspace = true
