[package]
name    = "identus-sdk-fuzz"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
hex            = "=0.4.3"
identus-crypto = { path = "../crates/crypto", default-features = false, features = [ "cose", "jwk-thumbprint" ] }
identus-did    = { path = "../crates/did" }
libfuzzer-sys  = "=0.4.13"
serde          = "=1.0.228"
serde_json     = "=1.0.150"

[[bin]]
name  = "did"
path  = "fuzz_targets/did.rs"
test  = false
doc   = false
bench = false

[[bin]]
name  = "did_url"
path  = "fuzz_targets/did_url.rs"
test  = false
doc   = false
bench = false

[[bin]]
name  = "public_jwk"
path  = "fuzz_targets/public_jwk.rs"
test  = false
doc   = false
bench = false

[[bin]]
name  = "public_cose"
path  = "fuzz_targets/public_cose.rs"
test  = false
doc   = false
bench = false

[workspace]
