[package]
name                   = "identus-did"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true

[dependencies]
identus-core.workspace   = true
identus-crypto.workspace = true
identus-derive.workspace = true
serde.workspace          = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
