#!/usr/bin/env python3
"""Generate and validate deterministic sdk-rust code-health evidence."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator


CONFIG_PATH = Path("docs/architecture/code-health.toml")
EXPECTED_SCHEMA = 1
ALLOWED_DISPOSITIONS = {
    "decompose",
    "deduplicate",
    "document-exception",
    "defer-with-owner",
}
GENERATED_MARKERS = (
    "@generated",
    "automatically generated",
    "generated by",
    "do not edit",
)


class AuditError(RuntimeError):
    """An invalid audit input or failed analysis."""


@dataclass(frozen=True)
class Span:
    start: int
    end: int


def canonical_json(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def sanitize_rust(source: str) -> str:
    """Blank comments and literals while retaining offsets and newlines."""
    chars = list(source)

    def blank(start: int, end: int) -> None:
        for index in range(start, end):
            if chars[index] != "\n":
                chars[index] = " "

    index = 0
    length = len(source)
    while index < length:
        if source.startswith("//", index):
            end = source.find("\n", index)
            end = length if end < 0 else end
            blank(index, end)
            index = end
            continue
        if source.startswith("/*", index):
            depth = 1
            end = index + 2
            while end < length and depth:
                if source.startswith("/*", end):
                    depth += 1
                    end += 2
                elif source.startswith("*/", end):
                    depth -= 1
                    end += 2
                else:
                    end += 1
            blank(index, end)
            index = end
            continue

        raw = re.match(r"(?:br|r)(#{0,255})\"", source[index:])
        if raw:
            hashes = raw.group(1)
            closing = '"' + hashes
            content_start = index + raw.end()
            found = source.find(closing, content_start)
            end = length if found < 0 else found + len(closing)
            blank(index, end)
            index = end
            continue

        quote_start = index
        if source.startswith('b"', index):
            index += 1
        if source[index:index + 1] == '"':
            end = index + 1
            while end < length:
                if source[end] == "\\":
                    end += 2
                    continue
                end += 1
                if source[end - 1] == '"':
                    break
            blank(quote_start, min(end, length))
            index = min(end, length)
            continue

        char_start = index
        if source.startswith("b'", index):
            index += 1
        if source[index:index + 1] == "'":
            # A lifetime has no closing quote immediately after one token.
            match = re.match(r"'[A-Za-z_][A-Za-z0-9_]*", source[index:])
            if match and source[index + len(match.group(0)):index + len(match.group(0)) + 1] != "'":
                index += len(match.group(0))
                continue
            end = index + 1
            while end < length:
                if source[end] == "\\":
                    end += 2
                    continue
                end += 1
                if source[end - 1] == "'":
                    break
            blank(char_start, min(end, length))
            index = min(end, length)
            continue
        index += 1
    return "".join(chars)


def matching_delimiter(text: str, start: int, opening: str, closing: str) -> int:
    depth = 0
    for index in range(start, len(text)):
        char = text[index]
        if char == opening:
            depth += 1
        elif char == closing:
            depth -= 1
            if depth == 0:
                return index
    raise AuditError(f"unbalanced {opening}{closing} delimiter at byte {start}")


CFG_TOKEN = re.compile(
    r'\s*(?:(?P<ident>[A-Za-z_][A-Za-z0-9_-]*)|(?P<string>"(?:\\.|[^"\\])*")|(?P<punct>[(),=]))'
)


class CfgParser:
    def __init__(self, text: str):
        self.tokens: list[str] = []
        offset = 0
        while offset < len(text):
            match = CFG_TOKEN.match(text, offset)
            if not match:
                if text[offset:].strip():
                    raise AuditError(f"unsupported cfg syntax: {text!r}")
                break
            self.tokens.append(match.group("ident") or match.group("string") or match.group("punct"))
            offset = match.end()
        self.index = 0

    def peek(self) -> str | None:
        return self.tokens[self.index] if self.index < len(self.tokens) else None

    def take(self) -> str:
        token = self.peek()
        if token is None:
            raise AuditError("unexpected end of cfg expression")
        self.index += 1
        return token

    def parse(self) -> bool | None:
        value = self.expression()
        if self.peek() is not None:
            raise AuditError(f"trailing cfg token {self.peek()!r}")
        return value

    def expression(self) -> bool | None:
        name = self.take()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]*", name):
            raise AuditError(f"expected cfg predicate, found {name!r}")
        if self.peek() == "=":
            self.take()
            self.take()
            return None
        if self.peek() != "(":
            return False if name == "test" else None

        self.take()
        values: list[bool | None] = []
        if self.peek() != ")":
            while True:
                values.append(self.expression())
                if self.peek() != ",":
                    break
                self.take()
                if self.peek() == ")":
                    break
        if self.take() != ")":
            raise AuditError("cfg group is not closed")

        if name == "all":
            if any(value is False for value in values):
                return False
            return True if all(value is True for value in values) else None
        if name == "any":
            if any(value is True for value in values):
                return True
            return False if all(value is False for value in values) else None
        if name == "not" and len(values) == 1:
            value = values[0]
            return None if value is None else not value
        return None


def cfg_value(attribute_body: str) -> bool | None:
    match = re.fullmatch(r"\s*cfg\s*\((.*)\)\s*", attribute_body, re.DOTALL)
    if not match:
        return None
    return CfgParser(match.group(1)).parse()


def skip_space(text: str, index: int) -> int:
    while index < len(text) and text[index].isspace():
        index += 1
    return index


def item_end(clean: str, index: int) -> int:
    """Find the end of an attributed Rust item in sanitized source."""
    index = skip_space(clean, index)
    while clean.startswith("#[", index):
        close = matching_delimiter(clean, index + 1, "[", "]")
        index = skip_space(clean, close + 1)

    parens = brackets = 0
    cursor = index
    while cursor < len(clean):
        char = clean[cursor]
        if char == "(":
            parens += 1
        elif char == ")":
            parens = max(0, parens - 1)
        elif char == "[":
            brackets += 1
        elif char == "]":
            brackets = max(0, brackets - 1)
        elif char == "{" and parens == 0 and brackets == 0:
            return matching_delimiter(clean, cursor, "{", "}") + 1
        elif char == ";" and parens == 0 and brackets == 0:
            return cursor + 1
        cursor += 1
    raise AuditError(f"could not find attributed item after byte {index}")


def merge_spans(spans: list[Span]) -> list[Span]:
    merged: list[Span] = []
    for span in sorted(spans, key=lambda item: (item.start, item.end)):
        if merged and span.start <= merged[-1].end:
            merged[-1] = Span(merged[-1].start, max(merged[-1].end, span.end))
        else:
            merged.append(span)
    return merged


def test_only_spans(source: str) -> list[Span]:
    clean = sanitize_rust(source)
    spans: list[Span] = []
    cursor = 0
    while cursor < len(clean):
        found = clean.find("#[", cursor)
        if found < 0:
            break
        close = matching_delimiter(clean, found + 1, "[", "]")
        body = source[found + 2:close]
        if cfg_value(body) is False:
            spans.append(Span(found, item_end(clean, close + 1)))
        cursor = close + 1
    return merge_spans(spans)


def span_lines(source: str, spans: list[Span]) -> set[int]:
    lines: set[int] = set()
    for span in spans:
        start = source.count("\n", 0, span.start) + 1
        end = source.count("\n", 0, max(span.start, span.end - 1)) + 1
        lines.update(range(start, end + 1))
    return lines


def rust_files(root: Path) -> tuple[list[Path], list[Path], list[Path]]:
    production: list[Path] = []
    external_tests: list[Path] = []
    generated: list[Path] = []
    for path in sorted((root / "crates").glob("*/**/*.rs")):
        relative = path.relative_to(root)
        parts = relative.parts
        if any(marker in "\n".join(path.read_text(encoding="utf-8").splitlines()[:10]).lower() for marker in GENERATED_MARKERS):
            generated.append(relative)
        elif (
            parts[2] in {"tests", "benches"}
            or (
                parts[2] == "src"
                and len(parts) >= 4
                and (parts[3] == "tests.rs" or parts[3] == "tests")
            )
        ):
            external_tests.append(relative)
        elif len(parts) >= 4 and parts[2] == "src":
            production.append(relative)
    return production, external_tests, generated


def engine_version(engine: str) -> str:
    completed = subprocess.run(
        [engine, "--version"], capture_output=True, text=True, check=False, timeout=10
    )
    if completed.returncode != 0:
        raise AuditError(f"{engine} --version failed: {completed.stderr.strip()}")
    return completed.stdout.strip()


def analyze_file(root: Path, path: Path, engine: str) -> dict[str, object]:
    completed = subprocess.run(
        [engine, "-p", str(path), "-m", "-O", "json"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
        timeout=30,
    )
    if completed.returncode != 0:
        raise AuditError(f"analysis failed for {path}: {completed.stderr.strip()}")
    try:
        return json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise AuditError(f"invalid analyzer JSON for {path}: {error}") from error


def function_spaces(space: dict[str, object]) -> Iterator[dict[str, object]]:
    if space.get("kind") == "function":
        yield space
    for child in space.get("spaces", []):
        yield from function_spaces(child)


def function_record(path: Path, item: dict[str, object], population: str) -> dict[str, object]:
    metrics = item["metrics"]
    loc = metrics["loc"]
    return {
        "cognitive": int(metrics["cognitive"]["sum"]),
        "cyclomatic": int(metrics["cyclomatic"]["sum"]),
        "end_line": int(item["end_line"]),
        "name": item["name"],
        "path": path.as_posix(),
        "population": population,
        "sloc": int(loc["sloc"]),
        "start_line": int(item["start_line"]),
    }


def load_config(root: Path) -> dict[str, object]:
    with (root / CONFIG_PATH).open("rb") as handle:
        config = tomllib.load(handle)
    if config.get("schema_version") != EXPECTED_SCHEMA:
        raise AuditError("unsupported code-health config schema")
    seen: set[str] = set()
    for hotspot in config.get("hotspots", []):
        identifier = hotspot.get("id")
        if not isinstance(identifier, str) or not identifier or identifier in seen:
            raise AuditError("hotspot ids must be unique non-empty strings")
        seen.add(identifier)
        if hotspot.get("disposition") not in ALLOWED_DISPOSITIONS:
            raise AuditError(f"hotspot {identifier} has invalid disposition")
        if not hotspot.get("owner") or not hotspot.get("evidence") or not hotspot.get("locations"):
            raise AuditError(f"hotspot {identifier} lacks owner, evidence, or locations")
    if not seen:
        raise AuditError("at least one hotspot classification is required")
    return config


def source_fingerprint(root: Path, paths: list[Path]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths):
        digest.update(path.as_posix().encode())
        digest.update(b"\0")
        digest.update((root / path).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def exact_revision(root: Path, requested: str | None) -> str:
    candidate = requested or "HEAD"
    resolved = subprocess.run(
        ["git", "rev-parse", "--verify", f"{candidate}^{{commit}}"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if not re.fullmatch(r"[0-9a-f]{40}", resolved):
        raise AuditError(f"Git did not resolve an exact commit for {candidate!r}")
    changed = subprocess.run(
        ["git", "diff", "--name-only", resolved, "--", "crates"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    changed_rust = [path for path in changed.stdout.splitlines() if path.endswith(".rs")]
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard", "--", "crates"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    untracked_rust = [path for path in untracked if path.endswith(".rs")]
    if changed.returncode != 0 or changed_rust or untracked_rust:
        raise AuditError(
            "authored Rust does not match the requested revision; commit it or audit an exact clean worktree"
        )
    return resolved


def audit(root: Path, revision: str | None) -> dict[str, object]:
    config = load_config(root)
    engine = str(config["engine"])
    expected = f"{engine} {config['engine_version']}"
    actual = engine_version(engine)
    if actual != expected:
        raise AuditError(f"expected exactly {expected}, found {actual}")

    production_paths, test_paths, generated_paths = rust_files(root)
    revision = exact_revision(root, revision)
    all_authored = production_paths + test_paths
    functions: list[dict[str, object]] = []
    counts = {
        "production": {"authored_nonblank_lines": 0, "files": 0, "functions": 0},
        "external_test": {"authored_nonblank_lines": 0, "files": 0, "functions": 0},
        "inline_test": {"authored_nonblank_lines": 0, "files": 0, "functions": 0},
    }
    modules: list[dict[str, object]] = []

    for path in production_paths:
        source = (root / path).read_text(encoding="utf-8")
        inline_lines = span_lines(source, test_only_spans(source))
        lines = source.splitlines()
        production_lines = sum(1 for number, line in enumerate(lines, 1) if line.strip() and number not in inline_lines)
        test_lines = sum(1 for number, line in enumerate(lines, 1) if line.strip() and number in inline_lines)
        if production_lines:
            counts["production"]["files"] += 1
            counts["production"]["authored_nonblank_lines"] += production_lines
            modules.append({"authored_nonblank_lines": production_lines, "path": path.as_posix()})
        if test_lines:
            counts["inline_test"]["files"] += 1
            counts["inline_test"]["authored_nonblank_lines"] += test_lines

        result = analyze_file(root, path, engine)
        for item in function_spaces(result):
            line = int(item["start_line"])
            population = "inline_test" if line in inline_lines else "production"
            counts[population]["functions"] += 1
            functions.append(function_record(path, item, population))

    for path in test_paths:
        source = (root / path).read_text(encoding="utf-8")
        counts["external_test"]["files"] += 1
        counts["external_test"]["authored_nonblank_lines"] += sum(
            1 for line in source.splitlines() if line.strip()
        )
        result = analyze_file(root, path, engine)
        for item in function_spaces(result):
            counts["external_test"]["functions"] += 1
            functions.append(function_record(path, item, "external_test"))

    attention = config["attention"]
    function_signals = [
        item
        for item in functions
        if item["population"] == "production"
        and (
            item["sloc"] > attention["function_sloc"]
            or item["cognitive"] > attention["cognitive"]
            or item["cyclomatic"] > attention["cyclomatic"]
        )
    ]
    function_signals.sort(key=lambda item: (item["path"], item["start_line"], item["name"]))
    module_signals = [
        item
        for item in modules
        if item["authored_nonblank_lines"] > attention["module_authored_nonblank_lines"]
    ]
    module_signals.sort(key=lambda item: item["path"])

    return {
        "analyzer": {
            "contract_version": config["contract_version"],
            "engine": engine,
            "engine_version": config["engine_version"],
        },
        "attention": attention,
        "generated_exclusions": [path.as_posix() for path in generated_paths],
        "hotspots": config["hotspots"],
        "populations": counts,
        "revision": revision,
        "schema_version": EXPECTED_SCHEMA,
        "signals": {
            "functions": function_signals,
            "modules": module_signals,
        },
        "source_fingerprint_sha256": source_fingerprint(root, all_authored),
    }


def validate_report(root: Path, path: Path) -> None:
    raw = path.read_text(encoding="utf-8")
    try:
        report = json.loads(raw)
    except json.JSONDecodeError as error:
        raise AuditError(f"invalid report JSON: {error}") from error
    if raw != canonical_json(report):
        raise AuditError("report is not canonical sorted/indented JSON")
    config = load_config(root)
    if report.get("schema_version") != EXPECTED_SCHEMA:
        raise AuditError("report schema version mismatch")
    analyzer = report.get("analyzer", {})
    for field in ("contract_version", "engine", "engine_version"):
        if analyzer.get(field) != config.get(field):
            raise AuditError(f"report analyzer {field} does not match config")
    if not re.fullmatch(r"[0-9a-f]{40}", str(report.get("revision", ""))):
        raise AuditError("report revision must be an exact 40-character Git SHA")
    if not re.fullmatch(r"[0-9a-f]{64}", str(report.get("source_fingerprint_sha256", ""))):
        raise AuditError("report source fingerprint must be SHA-256")
    if report.get("hotspots") != config.get("hotspots"):
        raise AuditError("report hotspot classifications are stale")
    for population in ("production", "external_test", "inline_test"):
        values = report.get("populations", {}).get(population, {})
        if any(not isinstance(values.get(field), int) or values[field] < 0 for field in ("files", "functions", "authored_nonblank_lines")):
            raise AuditError(f"invalid {population} population")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--revision")
    parser.add_argument("--check-report", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        if args.check_report:
            validate_report(root, args.check_report)
            print(f"code-health: report contract passed: {args.check_report}")
            return 0
        report = audit(root, args.revision)
        rendered = canonical_json(report)
        if args.output:
            args.output.write_text(rendered, encoding="utf-8")
            print(f"code-health: wrote {args.output}")
        else:
            sys.stdout.write(rendered)
        return 0
    except (AuditError, OSError, subprocess.SubprocessError) as error:
        print(f"code-health: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
