[package]
name                   = "identus-core"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish.workspace      = true

[dependencies]
identus-derive.workspace = true
serde.workspace          = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
