//! Centrally audited default resource policy for OID4VCI boundaries.

pub const MAX_CONFIGURABLE_JSON_DEPTH: usize = 64;

pub(super) const DEFAULT_OFFER_MAX_INVOCATION_BYTES: usize = 32_768;
pub(super) const DEFAULT_OFFER_MAX_EMBEDDED_JSON_BYTES: usize = 16_384;
pub(super) const DEFAULT_OFFER_MAX_REFERENCE_URI_BYTES: usize = 2_048;
pub(super) const DEFAULT_OFFER_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_OFFER_MAX_JSON_NODES: usize = 128;

pub(super) const DEFAULT_OFFER_SEMANTIC_MAX_ISSUER_BYTES: usize = 2_048;
pub(super) const DEFAULT_OFFER_SEMANTIC_MAX_CONFIGURATION_ID_BYTES: usize = 256;
pub(super) const DEFAULT_OFFER_SEMANTIC_MAX_CONFIGURATION_IDS: usize = 32;

pub(super) const DEFAULT_OFFER_GRANT_MAX_ISSUER_STATE_BYTES: usize = 2_048;
pub(super) const DEFAULT_OFFER_GRANT_MAX_PRE_AUTHORIZED_CODE_BYTES: usize = 4_096;
pub(super) const DEFAULT_OFFER_GRANT_MAX_AUTHORIZATION_SERVER_BYTES: usize = 2_048;
pub(super) const DEFAULT_OFFER_GRANT_MAX_TRANSACTION_DESCRIPTION_BYTES: usize = 1_200;
pub(super) const DEFAULT_OFFER_GRANT_MAX_TRANSACTION_CODE_LENGTH: usize = 64;
pub(super) const DEFAULT_TRANSACTION_CODE_INPUT_MAX_BYTES: usize = 256;

pub(super) const DEFAULT_PRE_AUTHORIZED_TOKEN_REQUEST_MAX_FORM_BYTES: usize = 16_384;
pub(super) const DEFAULT_PRE_AUTHORIZED_TOKEN_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;
pub(super) const DEFAULT_PRE_AUTHORIZED_TOKEN_HTTP_MAX_CACHE_CONTROL_BYTES: usize = 1_024;
pub(super) const DEFAULT_PRE_AUTHORIZED_TOKEN_HTTP_MAX_PRAGMA_BYTES: usize = 1_024;
pub(super) const DEFAULT_AUTHORIZATION_CODE_TOKEN_REQUEST_MAX_ENDPOINT_BYTES: usize = 2_048;
pub(super) const DEFAULT_AUTHORIZATION_CODE_TOKEN_REQUEST_MAX_FORM_BYTES: usize = 16_384;
pub(super) const DEFAULT_AUTHORIZATION_CODE_TOKEN_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;
pub(super) const DEFAULT_AUTHORIZATION_CODE_TOKEN_HTTP_MAX_CACHE_CONTROL_BYTES: usize = 1_024;
pub(super) const DEFAULT_AUTHORIZATION_CODE_TOKEN_HTTP_MAX_PRAGMA_BYTES: usize = 1_024;

pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_JSON_BYTES: usize = 65_536;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_JSON_NODES: usize = 1_024;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_ACCESS_TOKEN_BYTES: usize = 16_384;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_TOKEN_TYPE_BYTES: usize = 256;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_REFRESH_TOKEN_BYTES: usize = 16_384;
pub(super) const DEFAULT_TOKEN_RESPONSE_MAX_SCOPE_BYTES: usize = 4_096;

pub(super) const DEFAULT_TOKEN_AUTHORIZATION_MAX_DETAILS: usize = 32;
pub(super) const DEFAULT_TOKEN_AUTHORIZATION_MAX_TYPE_BYTES: usize = 128;
pub(super) const DEFAULT_TOKEN_AUTHORIZATION_MAX_CONFIGURATION_ID_BYTES: usize = 256;
pub(super) const DEFAULT_TOKEN_AUTHORIZATION_MAX_IDENTIFIERS_PER_DETAIL: usize = 64;
pub(super) const DEFAULT_TOKEN_AUTHORIZATION_MAX_IDENTIFIER_BYTES: usize = 2_048;

pub(super) const DEFAULT_TOKEN_ERROR_MAX_JSON_BYTES: usize = 32_768;
pub(super) const DEFAULT_TOKEN_ERROR_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_TOKEN_ERROR_MAX_JSON_NODES: usize = 512;
pub(super) const DEFAULT_TOKEN_ERROR_MAX_CODE_BYTES: usize = 256;
pub(super) const DEFAULT_TOKEN_ERROR_MAX_DESCRIPTION_BYTES: usize = 4_096;
pub(super) const DEFAULT_TOKEN_ERROR_MAX_URI_BYTES: usize = 2_048;

pub(super) const DEFAULT_CREDENTIAL_ERROR_MAX_JSON_BYTES: usize = 32_768;
pub(super) const DEFAULT_CREDENTIAL_ERROR_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_CREDENTIAL_ERROR_MAX_JSON_NODES: usize = 512;
pub(super) const DEFAULT_CREDENTIAL_ERROR_MAX_CODE_BYTES: usize = 256;
pub(super) const DEFAULT_CREDENTIAL_ERROR_MAX_DESCRIPTION_BYTES: usize = 4_096;
pub(super) const DEFAULT_CREDENTIAL_ERROR_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;

pub(super) const DEFAULT_CREDENTIAL_NONCE_MAX_JSON_BYTES: usize = 16_384;
pub(super) const DEFAULT_CREDENTIAL_NONCE_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_CREDENTIAL_NONCE_MAX_JSON_NODES: usize = 256;
pub(super) const DEFAULT_CREDENTIAL_NONCE_MAX_NONCE_BYTES: usize = 4_096;
pub(super) const DEFAULT_CREDENTIAL_NONCE_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;
pub(super) const DEFAULT_CREDENTIAL_NONCE_HTTP_MAX_CACHE_CONTROL_BYTES: usize = 4_096;

pub(super) const DEFAULT_JWT_CREDENTIAL_REQUEST_MAX_PROOFS: usize = 16;
pub(super) const DEFAULT_JWT_CREDENTIAL_REQUEST_MAX_PROOF_BYTES: usize = 16_384;
pub(super) const DEFAULT_JWT_CREDENTIAL_REQUEST_MAX_JSON_BODY_BYTES: usize = 262_144;
pub(super) const DEFAULT_JWT_CREDENTIAL_REQUEST_MAX_AUTHORIZATION_BYTES: usize = 16_384;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_REQUEST_MAX_JSON_BODY_BYTES: usize = 16_384;

pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_JSON_BYTES: usize = 32_768;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_JSON_NODES: usize = 512;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_MEMBERS: usize = 16;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_TRANSACTION_ID_BYTES: usize = 2_048;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_RESPONSE_MAX_INTERVAL_BYTES: usize = 128;

pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_JSON_BYTES: usize = 1_048_576;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_JSON_DEPTH: usize = 32;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_JSON_NODES: usize = 16_384;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_MEMBERS: usize = 32;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_CREDENTIALS: usize = 64;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_CREDENTIAL_MEMBERS: usize = 32;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_CREDENTIAL_BYTES: usize = 262_144;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_TOTAL_CREDENTIAL_BYTES: usize = 786_432;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_RESPONSE_MAX_NOTIFICATION_ID_BYTES: usize = 4_096;
pub(super) const DEFAULT_IMMEDIATE_CREDENTIAL_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;
pub(super) const DEFAULT_DEFERRED_CREDENTIAL_HTTP_MAX_CONTENT_TYPE_BYTES: usize = 1_024;

pub(super) const DEFAULT_ISSUER_METADATA_MAX_JSON_BYTES: usize = 131_072;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_JSON_NODES: usize = 1_024;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_ISSUER_BYTES: usize = 2_048;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_ENDPOINT_BYTES: usize = 2_048;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_AUTHORIZATION_SERVER_BYTES: usize = 2_048;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_AUTHORIZATION_SERVERS: usize = 16;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_CONFIGURATION_ID_BYTES: usize = 256;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_FORMAT_BYTES: usize = 128;
pub(super) const DEFAULT_ISSUER_METADATA_MAX_CONFIGURATIONS: usize = 128;

pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_JSON_BYTES: usize = 131_072;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_JSON_DEPTH: usize = 16;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_JSON_NODES: usize = 1_024;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_ISSUER_BYTES: usize = 2_048;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_ENDPOINT_BYTES: usize = 2_048;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_GRANT_TYPE_BYTES: usize = 256;
pub(super) const DEFAULT_AUTHORIZATION_SERVER_METADATA_MAX_GRANT_TYPES: usize = 32;
