name: File Hygiene

on:
  pull_request:
  push:
    branches: [develop]

jobs:
  editorconfig:
    name: File Hygiene (editorconfig)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@f2fa590df0c4a3039ee9daeb4f8c76a01641f42a # v4 asset support
        with:
          version: v4.0.0
      - name: EditorConfig Checker
        run: editorconfig-checker

  shell:
    name: Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          severity: warning

  markdown:
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23
        with:
          globs: "**/*.md"

  yaml:
    name: YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Yamllint
        uses: frenck/action-yamllint@e3e8cdef144eeb914883bd3c77f0333227140ffc # v1
